name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        wget https://github.com/atuline/WLED/archive/refs/heads/master.zip -O /tmp/mm.zip
        unzip /tmp/mm.zip -d /tmp
        find /tmp -maxdepth 1 -name "WLED-*" -type d >> wledfoldername
        mv `cat wledfoldername` /tmp/WLED-maindir
    - name: Run PlatformIO
      run: |
        cd /tmp/WLED-maindir
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:soundReactive_esp32dev' >>platformio.ini
        echo 'build_flags = ${env:soundReactive_esp32dev.build_flags} -D LEDPIN=12 -D BTNPIN=4 -D RLYPIN=15 -D AUDIOPIN=35 -D I2S_SDPIN=32 -D I2S_WSPIN=33 -D I2S_CKPIN=14 -D WLED_MAX_BUTTONS=2 -D ABL_MILLIAMPS_DEFAULT=5000 -D USERMOD_AUTO_SAVE -D USERMOD_PING_PONG_CLOCK -D USERMOD_WORDCLOCK -D USERMOD_ANALOG_CLOCK -D USERMOD_MULTI_RELAY -D USERMOD_SENSORSTOMQTT' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:soundReactive_esp32dev.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BMP280 Library @ 2.1.0' >>platformio.ini
        echo '  adafruit/Adafruit CCS811 Library @ 1.0.4' >>platformio.ini
        echo '  adafruit/Adafruit Si7021 Library @ 1.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
      env:
        PLATFORMIO_CI_SRC: /tmp/WLED-maindir
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        cp /tmp/WLED-maindir/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
